config/routes.rb
Rails.application.routes.draw do
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resource :cart, controller: "cart", only: [:show, :update, :edit] do
    member do
      post :add_product
      post :remove_product
      get :confirmation
      post :finish
    end
  end

  #post "cart/:id/finish" => "cart#finish", :as => "finish_cart"


  namespace :admin do
    root to: 'products#index'
    resources :categories
    resources :subcategories
    resources :products do
      collection do
        get :suprise
      end
    end 
      
    resources :orders
    resources :users
    resources :settings
  end
  
  resources :charges
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:create, :destroy]
  resources :categories
  resources :subcategories
  resources :products do
    collection do
      get :suprise
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  root to:'products#index'



 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  
  


  has_one_attached :picture

  validates :name, presence: true
  validates :code, presence: true, uniqueness: true
  validates :price, presence: true


  def thumb
   return self.picture.variant(resize: '500x500>', gravity: 'center')
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
     
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(20)


    #@q = Product.ransack(params[:q])
    #@products = @q.result(distinct: true).page(params[:page]).per(10)

    #@orders= @q.result(distinct: true).order("id DESC").page(params[:page]).per(20)
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Pomyślnie dodano produkt."
    else
      render action: :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to admin_products_path
    else
      render action: :edit
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  def suprise
    redirect_to root_path
  end
  

  private

  def product_params
    params.require(:product).permit(
      :name,
      :category_id,
      :subcategory_id,
      :description,
      :code,
      :price,
      :picture,
      :width,
      :height,
      :composition, 
      :quantity,
      :status
    )
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products=Product.all
    @setting =Setting.first
    @q = Product.ransack(params[:q])
    @products= @q.result(distinct: true).page(params[:page]).per(20)
  end

  def suprise
  end

  def show
    @product = Product.find(params[:id])
    @category = @product.category
    @setting =Setting.first
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.erb
<section>
  <header class="major"> 
   <!--  <h2>Latest products</h2>  -->
  </header>
   <div data-turbolinks="false">
     <%= paginate @products %>
   </div>  		
  <div class="posts">
    <% products.each_slice(3) do |slice| %>
      <% slice.each do |product| %>
        <%if product.status == true %>
          <article>
            <h3> <%= link_to product.name, product, style: 'color:#5f5A51;', data:{ turbolinks: "false" } %> </h3>
            <p><%= simple_format(truncate(product.description, length: 90))%></p>
					  
            <% if product.quantity != 0 %>
                <%= link_to add_product_cart_path(product_id: product.id), method: :post, class: "button big", remote: true do %>
                <span class="fa fa-shopping-cart"> Add to cart
              <% end %>
             <%end%>
             <div style="display: flex; justify-content: flex-end">
               <%= number_to_currency product.price %>
             </div>
             <ul class="actions"> 
               <li></li>
					   </ul>

          <div data-turbolinks="false">
            <a href=<%=product_path(product)%> class="image"><%=image_tag product.thumb if product.picture.attached? %> </a> 
          </div>
		     </article>
        <%end%> 
      <%end%>
    <%end%>
  </div>
</section>           
 <div data-turbolinks="false">                   						
   <%= paginate @products %>	
 </div>  

app/views/products/index.html.erb
  <!-- tak sie robi opisy --> 

	<section id="main">
        <%= render partial: 'products', locals: { products: @products } %>
	</section>
	

app/views/products/show.html.erb
  <section id="banner">
	  <div class="content">
      <div class="row">
        <div class="col-6 col-12-small">  
           <% if @product.picture.attached? %> 
          <!--   <img src="<%= url_for(@product.picture)%>" width="400" height="400">  -->

             <img id="myImg" src="<%= url_for(@product.picture)%>"  alt="<%=@product.name%>" style="width:100%;max-width:500px">

<!-- The Modal -->
<div id="myModal" class="modal close"> <!-- add classs close on picture, when you click on it will close -->
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>



           <%end%>
  

           <!-- lines below are with mg glass  -->
          <%# if @product.picture.attached? %> <!-- 
            <div class="img-magnifier-container">
              <img id="myimage" src="<%= url_for(@product.picture)%>" width="400" height="400">
            </div> 		 -->
          <%#end%>
        </div> 
         <div class="col-6 col-12-small">
          <header>
            <h3><%= @product.name %></h3>
            <p>Code: <%= @product.code%></p>
          </header>
          <hr class="major" />
            <p style="margin:0"><%= @product.description %></p>
          <hr class="major" />
            <p style="margin:0"> Composition: <%= @product.composition%></p>
            <p style="margin:0">Dimensions: <%=@product.height%>   x   <%=@product.width%></p>
            <p>Product Weight:  10 </p>
          <hr class="major" />
            <div class="row">
              <div class="col-6 col-12-small align-left"><%=number_to_currency(@product.price)%></div>
              <div class="col-6 col-12-small align-right">In Stock</div>
            </div>
          <hr class="major" />
          <ul class="actions" style="justify-content: center">
            <%= link_to add_product_cart_path(product_id: @product.id), method: :post, class: "button large", remote: true do %>
                <span class="fa fa-shopping-cart"> Add to cart
            <% end %>
          </ul>
        </div>
      </div>
		</div>

    
  <script>
    /* Initiate Magnify Function
    with the id of the image, and the strength of the magnifier glass:*/
   
   // magnify("myimage", 3);
  </script>



<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
  modal.style.display = "none";
}
</script>




















<!-- 
	<span class="image object">
          <%= image_tag(@product.picture) if @product.picture.attached? %> 
			</span>

-->
<!-- Wrapper 

<div class="col-md-12">
  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <div class="img-magnifier-container">
            <%= image_tag(@product.picture, width: 366, align:'center', hspace:'20', id: 'myimage') if @product.picture.attached? %> 
          </div>
        </div>
        <div class="col-md-6">  
          <h1 class="text-center"><p><%= @product.name %></p></h1> 
          <p1>Product code: <%= @product.code%></p>
          <p1>Product dimensions:  Width - <%=@product.width%>cm,    Height - <%=@product.height%>cm</p>
          <p class="lead"><%= number_to_currency(@product.price) %></p>
          <p class="lead"><%= @product.description %></p> 
          <p class="text-right">
            <%= link_to add_product_cart_path(product_id: @product.id), method: :post, class: "btn btn-primary" do %> 
              <span class="fa fa-shopping-cart"> Add to cart
            <% end %>
            <% if current_cart.line_items.present? %> 
              <%= link_to cart_path,class: "btn btn-primary" do %>
                <span class="fa fa-shopping-cart"> Go to cart
              <%end%>
            <%end%>
          </p>     
        </div>
      </div>
    </div>
  </div>
</div>

-->